services:
  db:
    image: postgres:latest
    container_name: banoffee
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: banoffee
      # TODO: get from .env
      POSTGRES_PASSWORD: 5up3r_s3cur3_p4ssw0rd
    ports:
      - "5432:5432"

volumes:
  postgres-data: null
