services:
  redis:
    image: redis
    container_name: redis
    command: redis-server
    ports:
      - "6379:6379"
  
  db:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: banoffee
      POSTGRES_PASSWORD: 5up3r_s3cur3_p4ssw0rd
    ports:
      - "5432:5432"

  test_redis:
    image: redis
    container_name: redis_testk
    command: redis-server
    ports:
      - "6380:6379"

  test_db:
    image: postgres:latest
    container_name: postgres_test
    restart: unless-stopped
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: test
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
    ports:
      - "5433:5432"      

volumes:
  postgres-data: null
