// Code generated by tygo. DO NOT EDIT.

//////////
// source: api.go

export interface API {
}

//////////
// source: resource.controller.go

export interface CreateResourcePayload {
  url: string;
  name: string;
  image_url?: string;
  author?: string;
  description?: string;
}
export interface SearchResourceRequest {
  Name: string;
}
export interface GetResourcePayload {
  Id: string;
  Url: string;
  Name: string;
}
export interface GetMyResourcesPayload {
  Limit: number /* int */;
  Offset: number /* int */;
}

//////////
// source: storage.go

export interface Repositories {
}
export type UserRepository = any;
export interface UserPostgresRepository {
}
export type ResourceRepository = any;
export interface ResourcePostgresRepository {
}
export interface UserAuthInfo {
  id: any /* uuid.UUID */;
  email: string;
}

//////////
// source: types.go

export interface User {
  id: any /* uuid.UUID */;
  email: string;
  username: string;
  avatar_url?: string;
  header_url?: string;
  bio?: string;
  created_at: any /* time.Time */;
}
export interface Resource {
  id: any /* uuid.UUID */;
  url: string;
  name: string;
  image_url?: string;
  author?: string;
  description?: string;
  status?: string;
  review_rating?: string;
  review_comment?: string;
  created_at: any /* time.Time */;
}

//////////
// source: user.controller.go

export interface LoginPayload {
  email: string;
  password: string;
}
export interface RegisterRequest {
  email: string;
  username: string;
  password: string;
  avatar_url?: string | null;
  header_url?: string | null;
  bio?: string | null;
}
export interface SaveResourcePayload {
  status?: string;
  review_rating?: string;
  review_comment?: string;
}
