name: Pull Request CI

on: [pull_request]

# TODO: cache dependencies with Nix
jobs:
  install:
    name: Installing Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install Extension/Web dependencies
        run: nix develop && yarn install
      
      - name: Install Server dependencies
        run: nix develop && cd apps/server && go get .
      
      - name: Install Resources Recommender dependencies
        run: nix develop && cd apps/resources-recommender && python3 -m venv . && source bin/activate && pip3 install .

  linter:
    name: Run linter checks
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install Extension/Web dependencies
        run: nix develop && yarn install
        
      - name: Install Server dependencies
        run: nix develop && cd apps/server && go get .
        
      # - name: Install Resources Recommender dependencies
      #   run: nix develop && cd apps/resources-recommender && python3 -m venv . && source bin/activate && pip3 install .
      
      - name: Run Extension/Web linter checks
        run: nix develop && cd apps/web && yarn lint
      
      - name: Run Server linter checks
        run: nix develop && cd apps/server && golangci-lint run
  
  build:
    name: Run Builds
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install Extension/Web dependencies
        run: nix develop && yarn install
          
      - name: Install Server dependencies
        run: nix develop && cd apps/server && go get .
          
      - name: Install Resources Recommender dependencies
        run: nix develop && cd apps/resources-recommender && python3 -m venv . && source bin/activate && pip3 install .

      - name: Run Web build
        run: nix develop && cd apps/web && yarn build
      
      - name: Run Extension build
        run: nix develop && cd apps/extension/web-extension && yarn build
      
      - name: Run Server build
        run: nix develop && cd apps/server && go build
      
      - name: Run Resources Recommender build
        run: nix develop && cd apps/resources-recommender && python3 -m venv . && source bin/activate && mypy main.py

  # TODO: Needs to setup a local postgres to run this
  # tests:
  #   name: Run Tests
  #   runs-on: ubuntu-latest
  #   needs: install
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 2

  #     - name: Install Server dependencies
  #       run: nix develop && cd apps/server && go get .
        
  #     - name: Run Server tests
  #       run: nix develop && cd apps/server && go test